set-option -sa terminal-overrides ",xterm*:Tc"
set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'

unbind c
bind c source-file ~/.zshrc

unbind r
bind r source-file ~/.tmux.conf \; display "Config reloaded"

unbind '"'
bind-key | split-window -h

unbind %
bind-key - split-window -v

# Enable mouse
set -g mouse on

# Panel navegation 
bind-key h select-pane -L
bind-key j select-pane -U
bind-key k select-pane -D
bind-key l select-pane -R


# List of plugins
set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @plugin 'swaroopch/tmux-pomodoro'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"

# Make the status line pretty and add some modules
set -g focus-event on
set -g status-right-length 100
set -g status-left-length 100
set -g status-left "#{E:@catppuccin_status_application}"
set -g status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -ag status-right "#{E:@catppuccin_status_date_time}"

# Update WezTerm tab title when switching, attaching, or creating a tmux session
set-hook -g client-session-changed 'run-shell "if [ -n \"$WEZTERM_PANE\" ]; then printf \"\\033Ptmux;\\033\\033]1337;SetUserVar=tmux_session=\$(printf '"'"'%s'"'"' \"#S\" | base64)\\007\\033\\\\\" > \"\$(tmux display-message -p \"#{client_tty}\")\"; fi"'
set-hook -g client-attached 'run-shell "if [ -n \"$WEZTERM_PANE\" ]; then printf \"\\033Ptmux;\\033\\033]1337;SetUserVar=tmux_session=\$(printf '"'"'%s'"'"' \"#S\" | base64)\\007\\033\\\\\" > \"\$(tmux display-message -p \"#{client_tty}\")\"; fi"'
set-hook -g after-new-session 'run-shell "if [ -n \"$WEZTERM_PANE\" ]; then printf \"\\033Ptmux;\\033\\033]1337;SetUserVar=tmux_session=\$(printf '"'"'%s'"'"' \"#S\" | base64)\\007\\033\\\\\" > \"\$(tmux display-message -p \"#{client_tty}\")\"; fi"'
set-hook -g client-detached 'run-shell "printf \"\\033]2;\\007\" > \"$(tmux display-message -p \"#{client_tty}\")\"; if [ -n \"$WEZTERM_PANE\" ]; then printf \"\\033]1337;SetUserVar=tmux_session=\\007\" > \"$(tmux display-message -p \"#{client_tty}\")\"; fi"'
set-hook -g session-closed 'run-shell "if [ -n \"$WEZTERM_PANE\" ]; then printf \"\\033]1337;SetUserVar=tmux_session=\\007\" > /dev/tty; fi"'

# My popups config
bind-key l display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "lazygit"

bind-key c split-window -h -c "#{pane_current_path}" "claude"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'


